repos:
  - repo: local
    hooks:
      - id: ruff
        name: Run ruff
        entry: ruff check --fix .
        language: python
        files: \.py$
      - id: black
        name: Run black
        entry: black .
        language: python
        files: \.py$
      - id: bandit
        name: Run bandit
        entry: bandit -c pyproject.toml -r .
        language: python
        files: \.py$
