repos:
  - repo: local
    hooks:
      - id: black
        name: Run black
        entry: black .
        language: python
        files: \.py$
        exclude: migrations
      - id: isort
        name: Run isort
        entry: isort .
        language: python
        files: \.py$
        exclude: migrations
      - id: flake8
        name: Run flake8
        entry: flake8 .
        language: python
        files: \.py$
        exclude: migrations
