version: '3.8'

services:
  redis:
    image: redis:7-alpine

  rabbitmq:
    image: rabbitmq:3.11-management

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=dev
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - SECRET_KEY=697be90749590b29ad92e0f8b5a0e7d11cf895403af9858ba7813bd51aac5795
      - DATABASE_URL=mysql+asyncmy://root@db/dev
      - DATABASE_TEST_URL=sqlite+aiosqlite://
      - BROKER_URL=amqp://rabbitmq
      - RESULT_BACKEND=redis://redis
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbitmq
    command: ./scripts/wait-for-it.sh -t 30 db:3306 -- gunicorn -b 0.0.0.0 -k uvicorn.workers.UvicornWorker app.main:app

  worker:
    build: .
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - SECRET_KEY=697be90749590b29ad92e0f8b5a0e7d11cf895403af9858ba7813bd51aac5795
      - DATABASE_URL=mysql+asyncmy://root@db/dev
      - DATABASE_TEST_URL=sqlite+aiosqlite://
      - BROKER_URL=amqp://rabbitmq
      - RESULT_BACKEND=redis://redis
    volumes:
      - .:/code
    depends_on:
      - web
    command: ./scripts/wait-for-it.sh -t 10 rabbitmq:5672 -- celery -A app.background.worker worker --without-heartbeat --without-gossip --without-mingle -l INFO

volumes:
  mysql_data: null
