version: '3.9'

services:
  redis:
    image: redis:6-alpine

  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - 5672:5672
      - 15672:15672
  
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    expose:
      - 5432

  web:
    build: .
    command: gunicorn -b 0.0.0.0 -k uvicorn.workers.UvicornWorker app.main:app
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@db:5432/web_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/web_test
      - CELERY_BROKER_URL=amqp://rabbitmq
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/code
    ports:
      - 8004:8000
    depends_on:
    - redis
    - rabbitmq
    - db
  
  worker:
    build: .
    command: celery worker -A app.background.worker -l INFO
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@db:5432/web_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/web_test
      - CELERY_BROKER_URL=amqp://rabbitmq
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/code
    depends_on:
      - web
  
  dashboard:
    build: .
    command: flower -A app.background.tasks.celery
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - 5556:5555
    depends_on:
      - worker

volumes:
  postgresql_data: