version: '3.8'

services:
  redis:
    image: redis:6-alpine

  rabbitmq:
    image: rabbitmq:3.8-management
  
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    expose:
      - 5432

  web:
    build: .
    command: gunicorn -b 0.0.0.0 -k uvicorn.workers.UvicornWorker app.main:app
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@db:5432/web_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/web_test
      # - BROKER_URL=<replace_it_with_your_rabbitmq_url>
      # - RESULT_BACKEND=<replace_it_with_your_redis_url>
    volumes:
      - .:/code
    ports:
      - 8004:8000
    depends_on:
    - redis
    - rabbitmq
    - db
  
  worker:
    build: .
    command: celery -A app.background.worker worker -l INFO
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@db:5432/web_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/web_test
      # - BROKER_URL=<replace_it_with_your_rabbitmq_url>
      # - RESULT_BACKEND=<replace_it_with_your_redis_url>
    volumes:
      - .:/code
    depends_on:
      - web

volumes:
  postgresql_data: