[tool.black]
exclude = '''
/(
    \.mypy_cache
  | \.pytest_cache
  | migrations
)/
'''
line-length = 119

[tool.flake8]
exclude = [".mypy_cache", ".pytest_cache", "migrations"]
max-line-length = 119

[tool.isort]
profile = "black"
skip_glob = [".mypy_cache", ".pytest_cache", "migrations"]

[tool.poetry]
authors = ["Evgeni Sautin <evgeni.sautin@gmail.com>"]
description = "Test-driven development with FastAPI and Docker"
name = "fastapi-tdd-docker"
version = "0.2.0"

[tool.poetry.dependencies]
aerich = "^0.5.3"
asyncpg = "^0.23.0"
celery = "^5.1.0"
fastapi = "^0.65.1"
gunicorn = "^20.1.0"
httptools = "^0.2.0"
newspaper3k = "^0.2.8"
python = "^3.9"
redis = "^3.5.3"
requests = "^2.25.1"
tortoise-orm = "^0.17.4"
uvicorn = "^0.14.0"
uvloop = "^0.15.2"

[tool.poetry.dev-dependencies]
bandit = "^1.7.0"
# Fixed version due to incompatibility issues with the latest one.
black = "21.5b2"
flake9 = "^3.8.3"
isort = "^5.8.0"
mypy = "^0.812"
pylint = "^2.8.3"
pytest = "^6.2.4"
pytest-asyncio = "^0.15.1"
pytest-cov = "^2.12.1"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
