[tool.black]
exclude = '''
/(
    \.mypy_cache
  | \.pytest_cache
  | migrations
)/
'''
line-length = 119

[tool.isort]
profile = "black"
skip_glob = [".mypy_cache", ".pytest_cache", "migrations"]

[tool.coverage]
[tool.coverage.run]
omit = ["*tests*"]

[tool.poetry]
authors = ["Evgeni Sautin <evgeni.sautin@gmail.com>"]
description = "Test-driven development with FastAPI and Docker"
name = "fastapi-tdd-docker"
version = "2.0.0"

[tool.poetry.dependencies]
aerich = "^0.6.3"
celery = "^5.2.6"
email-validator = "^1.1.3"
fastapi = "^0.75.1"
gunicorn = "^20.1.0"
newspaper3k = "^0.2.8"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python = "^3.10"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
python-multipart = "^0.0.5"
redis = "^4.2.2"
tortoise-orm = {extras = ["asyncpg", "aiomysql"], version = "^0.19.0"}
uvicorn = {extras = ["standard"], version = "^0.17.6"}

[tool.poetry.dev-dependencies]
bandit = "^1.7.4"
black = "^22.3.0"
flake8 = "^4.0.1"
isort = "^5.10.1"
mypy = "^0.942"
pre-commit = "^2.18.1"
pylint = "^2.13.5"
pytest = "^7.1.1"
pytest-asyncio = "^0.18.3"
pytest-cov = {extras = ["toml"], version = "^3.0.0"}

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
