"""Add type annotations

Revision ID: 0abf27951d83
Revises: 4f5f4beb31b0
Create Date: 2023-05-02 06:32:28.696919

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0abf27951d83"
down_revision = "4f5f4beb31b0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("summaries", "url", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("summaries", "summary", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("summaries", "user_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "summaries",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "summaries",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(op.f("ix_summaries_url"), "summaries", ["url"], unique=False)
    op.alter_column("users", "full_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "full_name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(op.f("ix_summaries_url"), table_name="summaries")
    op.alter_column(
        "summaries",
        "modified_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "summaries",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("summaries", "user_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("summaries", "summary", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("summaries", "url", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
