"""changed field to Text

Revision ID: 99dd5be698b4
Revises: 15f3a3a3ee66
Create Date: 2023-10-21 12:43:32.074073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "99dd5be698b4"
down_revision = "15f3a3a3ee66"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "summaries", "summary", existing_type=mysql.VARCHAR(length=255), type_=sa.Text(), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "summaries", "summary", existing_type=sa.Text(), type_=mysql.VARCHAR(length=255), existing_nullable=False
    )
    # ### end Alembic commands ###
