name: Continuous Integration and Delivery

on: [push]

env:
  WEB_IMAGE: docker.pkg.github.com/$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')/web
  WORKER_IMAGE: docker.pkg.github.com/$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')/worker

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.3.4
      - name: Log in to GitHub Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull images
        run: |
          docker pull ${{ env.WEB_IMAGE }}-builder:latest || true
          docker pull ${{ env.WEB_IMAGE }}-final:latest || true
          docker pull ${{ env.WORKER_IMAGE }}-builder:latest || true
          docker pull ${{ env.WORKER_IMAGE }}-final:latest || true
      - name: Build images
        run: |
          docker build \
            --target builder \
            --cache-from ${{ env.WEB_IMAGE }}-builder:latest \
            --tag ${{ env.WEB_IMAGE }}-builder:latest \
            --file ./Dockerfile.web \
            "."
          docker build \
            --cache-from ${{ env.WEB_IMAGE }}-final:latest \
            --tag ${{ env.WEB_IMAGE }}-final:latest \
            --file ./Dockerfile.web \
            "."
          docker build \
            --target builder \
            --cache-from ${{ env.WORKER_IMAGE }}-builder:latest \
            --tag ${{ env.WORKER_IMAGE }}-builder:latest \
            --file ./Dockerfile.worker \
            "."
          docker build \
            --cache-from ${{ env.WORKER_IMAGE }}-final:latest \
            --tag ${{ env.WORKER_IMAGE }}-final:latest \
            --file ./Dockerfile.worker \
            "."
      - name: Push images
        run: |
          docker push ${{ env.WEB_IMAGE }}-builder:latest
          docker push ${{ env.WEB_IMAGE }}-final:latest
          docker push ${{ env.WORKER_IMAGE }}-builder:latest
          docker push ${{ env.WORKER_IMAGE }}-final:latest
  test:
    name: Test Docker Images
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.3.4
      - name: Log in to GitHub Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull images
        run: |
          docker pull ${{ env.WEB_IMAGE }}-builder:latest || true
          docker pull ${{ env.WEB_IMAGE }}-final:latest || true
          docker pull ${{ env.WORKER_IMAGE }}-builder:latest || true
          docker pull ${{ env.WORKER_IMAGE }}-final:latest || true
      - name: Build images
        run: |
          docker build \
            --target builder \
            --cache-from ${{ env.WEB_IMAGE }}-builder:latest \
            --tag ${{ env.WEB_IMAGE }}-builder:latest \
            --file ./Dockerfile.web \
            "."
          docker build \
            --cache-from ${{ env.WEB_IMAGE }}-final:latest \
            --tag ${{ env.WEB_IMAGE }}-final:latest \
            --file ./Dockerfile.web \
            "."
          docker build \
            --target builder \
            --cache-from ${{ env.WORKER_IMAGE }}-builder:latest \
            --tag ${{ env.WORKER_IMAGE }}-builder:latest \
            --file ./Dockerfile.worker \
            "."
          docker build \
            --cache-from ${{ env.WORKER_IMAGE }}-final:latest \
            --tag ${{ env.WORKER_IMAGE }}-final:latest \
            --file ./Dockerfile.worker \
            "."
      - name: Run containers
        run: docker-compose up -d
      - name: Install requirements
        run: docker-compose exec -T web pip install black flake9 isort pytest pytest-asyncio
      - name: Pytest
        run: docker-compose exec -T web pytest .
      - name: Flake8
        run: docker-compose exec -T web flake8 .
      - name: Black
        run: docker-compose exec -T web black . --check
      - name: isort
        run: docker-compose exec -T web isort . --check-only

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: [build, test]
    env:
      HEROKU_APP_NAME: guarded-waters-54698
      HEROKU_REGISTRY_WEB_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web
      HEROKU_REGISTRY_WORKER_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/worker
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.3.4
      - name: Log in to GitHub Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull images
        run: |
          docker pull ${{ env.WEB_IMAGE }}-builder:latest || true
          docker pull ${{ env.WEB_IMAGE }}-final:latest || true
          docker pull ${{ env.WORKER_IMAGE }}-builder:latest || true
          docker pull ${{ env.WORKER_IMAGE }}-final:latest || true
      - name: Build images
        run: |
          docker build \
            --target builder \
            --cache-from ${{ env.WEB_IMAGE }}-builder:latest \
            --tag ${{ env.WEB_IMAGE }}-builder:latest \
            --file ./Dockerfile.web \
            "."
          docker build \
            --cache-from ${{ env.WEB_IMAGE }}-final:latest \
            --tag ${{ env.WEB_IMAGE }}:latest \
            --tag ${{ env.HEROKU_REGISTRY_WEB_IMAGE }}:latest \
            --file ./Dockerfile.web \
            "."
          docker build \
            --target builder \
            --cache-from ${{ env.WORKER_IMAGE }}-builder:latest \
            --tag ${{ env.WORKER_IMAGE }}-builder:latest \
            --file ./Dockerfile.worker \
            "."
          docker build \
            --cache-from ${{ env.WORKER_IMAGE }}-final:latest \
            --tag ${{ env.WORKER_IMAGE }}:latest \
            --tag ${{ env.HEROKU_REGISTRY_WORKER_IMAGE }}:latest \
            --file ./Dockerfile.worker \
            "."
      - name: Log in to the Heroku Container Registry
        run: docker login -u _ -p ${HEROKU_AUTH_TOKEN} registry.heroku.com
        env:
          HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
      - name: Push to the registry
        run: |
          docker push ${{ env.HEROKU_REGISTRY_WEB_IMAGE }}:latest
          docker push ${{ env.HEROKU_REGISTRY_WORKER_IMAGE }}:latest
      - name: Set environment variables
        run: |
          echo "HEROKU_REGISTRY_WEB_IMAGE=${{ env.HEROKU_REGISTRY_WEB_IMAGE }}" >> $GITHUB_ENV
          echo "HEROKU_REGISTRY_WORKER_IMAGE=${{ env.HEROKU_REGISTRY_WORKER_IMAGE }}" >> $GITHUB_ENV
          echo "HEROKU_AUTH_TOKEN=${{ secrets.HEROKU_AUTH_TOKEN }}" >> $GITHUB_ENV
      - name: Release
        run: |
          chmod +x ./release.sh
          ./release.sh
